#ifndef CONFIG_H
#define CONFIG_H

#define MICROCONTROLLER_ESP32 1
#define MICROCONTROLLER_TEENSY 2
#define MICROCONTROLLER_STM32 3

#define MICROCONTROLLER MICROCONTROLLER_ESP32

extern const char *CONFIG;

#endif
